version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    container_name: scalping-bot
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - docker/.env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network: